data "aws_ami" "ami" {
  most_recent      = true
  name_regex       = "devops-practice-ansible"            //  we replaced The old line because we need to install ansible on every machine. so instead of doing it manually, we created a image from an instance and make it available to our account. so no need to install ansible in every system we create. 
  owners           = [data.aws_caller_identity.current.account_id]
}

//The above data block is prerequisite for allowing to create ec2 instance

resource "aws_spot_instance_request" "ec2" {  
  ami                     = data.aws_ami.ami.image_id
  instance_type           = var.instance_type
  vpc_security_group_ids  = [aws_security_group.sg.id]

  tags = {
    Name = var.component
  }
    
}

// aws_ec2_tag is needed to inherit the tags generated by spot request
resource "aws_ec2_tag" "ec2" {
  resource_id = aws_spot_instance_request.ec2.spot_instance_id
  for_each = aws_spot_instance_request.ec2.tags
  key = each.key
  value = each.value
}

resource "null_resource" "provisioner" {
  depends_on = [aws_spot_instance_request.ec2] //we have included this line because remote-exec will take some time. so we have included depends_on parameter. This will ensure you after the instance is fully created which we mentioned in depends on parameter, then only remote-exec will request to connect.  
    provisioner "remote-exec" {
    connection {
          host     = aws_spot_instance_request.ec2.public_ip
          user     = "centos"
          password = "DevOps321"
    }
      inline = [
        "ansible-pull -i localhost, -U https://github.com/Siva-Sai-Deepak-Pulipaka/roboshop-ansible.git roboshop.yml -e role_name=${var.component}"
        
      ]

  }

}


resource "aws_security_group" "sg" {
  name        = "${var.component}-${var.env}-sg"
  description = "Allow TLS inbound traffic"
  
  ingress {
    description      = "Allowing all for incoming"
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.component}-${var.env}-sg"
  }
}

resource "aws_route53_record" "record" {
  zone_id = "Z017354339FNHXHAHU536"
  name    = "${var.component}-dev.easydevops.online"
  type    = "A"
  ttl     = 30
  records = [aws_spot_instance_request.ec2.private_ip]
}

variable "component" {}
variable "instance_type" {}
variable "env" {
  default = "dev"
}
variable "password" {}
